### PR TITLE
include support for javax.validation

### PR DESCRIPTION
**Pull request by hatzlj**
- introduce value extractor
- add test-case

see: OpenAPITools/jackson-databind-nullable#2

### CODE REVIEW

**Comment by hatzlj** [comment]
don't know why CI failed on ed9814e and 7b8f1c5, since 4511de6 built normally.

**Comment by hatzlj** [comment]
@cbornet could you please trigger a rebuild (did not find a possibility for triggering a rebuild by myself), since I didn't change any code related to the build error. 
Thx
Jakob

**Comment by cbornet** [comment]
Yes something is wrong with CI since #4. I don't know why it was not detected before merge...

**Comment by hatzlj** [comment]
thx

**Comment by cbornet** [comment]
Thanks to you ! :smile:

**Comment by hatzlj** [comment]
@cbornet do you know when there will be a release available in maven central. can I support you in any way with this?

**Pull request merged**
